### ISSUE TITLE
Logo Design for commit-time

### ISSUE THREAD

**Issue by zuurw** [karagenit/commit-time#7]
Hi @karagenit , my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by karagenit** [comment]
Hey @zuurw , that sounds awesome! If you already have some designs in mind, go for it - otherwise if you need some inspiration, I'm happy to help.

Thanks!
Caleb

**Comment by zuurw** [comment]
Hi @karagenit, do you have something in your mind for the logo? do you have any request? Where can I get inspired?

Best Regards!

**Comment by karagenit** [comment]
I don't have any particular requests, you might look at either the [git logo](https://git-scm.com/images/logos/1color-orange-lightbg@2x.png) or something like the Github [contributions graph](http://avalonstar.com/journal/2014/the-graphs-are-always-greener/contributions.png), or of course something generally related to time such as a clock.

Thanks again!

**Comment by zuurw** [comment]
Hi @karagenit, I create this design for this project, the concept it´s  a clock that incoporate the git logo and the squares of the contributions graph.

See if you like it, If not I can do a new one or make some changes.

Best Regards!

![proposal](https://user-images.githubusercontent.com/40801473/43370630-56c30264-937a-11e8-8c12-47a06a648a13.png)

**Comment by karagenit** [comment]
That looks great! I think my favorite is the first one - if you want to submit a PR to add it to the README that'd be awesome.

Thanks again!

**Comment by zuurw** [comment]
Hello @karagenit, just to say that I submit a PR with the logo files and update the README.

Best Regards!

**Comment by karagenit** [comment]
Awesome, thanks!
